// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgId.proto

package com.game.rpc.message.st;

public final class MsgId {
  private MsgId() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *消息ID
   *1000~4000  内部协议
   *1000~1500  房间
   *5000~ 5999 大厅协议
   * </pre>
   *
   * Protobuf enum {@code com.game.rpc.message.st.EN_MessageId}
   */
  public enum EN_MessageId
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *错误的消息ID
     * </pre>
     *
     * <code>E_ERROR_ID = 0;</code>
     */
    E_ERROR_ID(0),
    /**
     * <pre>
     *1000~1500  房间
     * </pre>
     *
     * <code>E_ROOM_START = 1000;</code>
     */
    E_ROOM_START(1000),
    /**
     * <pre>
     *房间创建
     * </pre>
     *
     * <code>E_ROOM_CREATE = 1001;</code>
     */
    E_ROOM_CREATE(1001),
    /**
     * <pre>
     *房间心跳
     * </pre>
     *
     * <code>E_ROOM_HEART = 1002;</code>
     */
    E_ROOM_HEART(1002),
    /**
     * <pre>
     *房间状态改变
     * </pre>
     *
     * <code>E_ROOM_STATUS_CHANGE = 1003;</code>
     */
    E_ROOM_STATUS_CHANGE(1003),
    /**
     * <pre>
     *房间关关闭
     * </pre>
     *
     * <code>E_ROOM_CLOSE = 1004;</code>
     */
    E_ROOM_CLOSE(1004),
    /**
     * <pre>
     *玩家进入
     * </pre>
     *
     * <code>E_ROOM_ENTER_PLAYER = 1005;</code>
     */
    E_ROOM_ENTER_PLAYER(1005),
    /**
     * <pre>
     *玩家退出
     * </pre>
     *
     * <code>E_ROOM_QUIT_PLAYER = 1006;</code>
     */
    E_ROOM_QUIT_PLAYER(1006),
    /**
     * <pre>
     *战报
     * </pre>
     *
     * <code>E_ROOM_BATTLE_REPORT = 1007;</code>
     */
    E_ROOM_BATTLE_REPORT(1007),
    /**
     * <code>E_ROOM_END = 1500;</code>
     */
    E_ROOM_END(1500),
    /**
     * <pre>
     *5000~ 5999 大厅协议
     * </pre>
     *
     * <code>E_LOGIN_START = 5000;</code>
     */
    E_LOGIN_START(5000),
    /**
     * <pre>
     *登录请求
     * </pre>
     *
     * <code>E_LOGIN = 5001;</code>
     */
    E_LOGIN(5001),
    /**
     * <pre>
     *登出请求
     * </pre>
     *
     * <code>E_LOGOUT = 5002;</code>
     */
    E_LOGOUT(5002),
    /**
     * <pre>
     *创建账号
     * </pre>
     *
     * <code>E_CREATE_ACCOUNT = 5003;</code>
     */
    E_CREATE_ACCOUNT(5003),
    /**
     * <pre>
     *创建角色
     * </pre>
     *
     * <code>E_CREATE_PLAYER = 5004;</code>
     */
    E_CREATE_PLAYER(5004),
    /**
     * <code>E_LOGIN_END = 5999;</code>
     */
    E_LOGIN_END(5999),
    /**
     * <code>E_LOBBY_START = 6000;</code>
     */
    E_LOBBY_START(6000),
    /**
     * <code>E_ENTER_LOBBY = 6001;</code>
     */
    E_ENTER_LOBBY(6001),
    /**
     * <pre>
     *NOTIFY 25000~29999
     * </pre>
     *
     * <code>NOTIFY_COMMON_ERROR = 29999;</code>
     */
    NOTIFY_COMMON_ERROR(29999),
    /**
     * <code>E_LOBBY_END = 30000;</code>
     */
    E_LOBBY_END(30000),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *错误的消息ID
     * </pre>
     *
     * <code>E_ERROR_ID = 0;</code>
     */
    public static final int E_ERROR_ID_VALUE = 0;
    /**
     * <pre>
     *1000~1500  房间
     * </pre>
     *
     * <code>E_ROOM_START = 1000;</code>
     */
    public static final int E_ROOM_START_VALUE = 1000;
    /**
     * <pre>
     *房间创建
     * </pre>
     *
     * <code>E_ROOM_CREATE = 1001;</code>
     */
    public static final int E_ROOM_CREATE_VALUE = 1001;
    /**
     * <pre>
     *房间心跳
     * </pre>
     *
     * <code>E_ROOM_HEART = 1002;</code>
     */
    public static final int E_ROOM_HEART_VALUE = 1002;
    /**
     * <pre>
     *房间状态改变
     * </pre>
     *
     * <code>E_ROOM_STATUS_CHANGE = 1003;</code>
     */
    public static final int E_ROOM_STATUS_CHANGE_VALUE = 1003;
    /**
     * <pre>
     *房间关关闭
     * </pre>
     *
     * <code>E_ROOM_CLOSE = 1004;</code>
     */
    public static final int E_ROOM_CLOSE_VALUE = 1004;
    /**
     * <pre>
     *玩家进入
     * </pre>
     *
     * <code>E_ROOM_ENTER_PLAYER = 1005;</code>
     */
    public static final int E_ROOM_ENTER_PLAYER_VALUE = 1005;
    /**
     * <pre>
     *玩家退出
     * </pre>
     *
     * <code>E_ROOM_QUIT_PLAYER = 1006;</code>
     */
    public static final int E_ROOM_QUIT_PLAYER_VALUE = 1006;
    /**
     * <pre>
     *战报
     * </pre>
     *
     * <code>E_ROOM_BATTLE_REPORT = 1007;</code>
     */
    public static final int E_ROOM_BATTLE_REPORT_VALUE = 1007;
    /**
     * <code>E_ROOM_END = 1500;</code>
     */
    public static final int E_ROOM_END_VALUE = 1500;
    /**
     * <pre>
     *5000~ 5999 大厅协议
     * </pre>
     *
     * <code>E_LOGIN_START = 5000;</code>
     */
    public static final int E_LOGIN_START_VALUE = 5000;
    /**
     * <pre>
     *登录请求
     * </pre>
     *
     * <code>E_LOGIN = 5001;</code>
     */
    public static final int E_LOGIN_VALUE = 5001;
    /**
     * <pre>
     *登出请求
     * </pre>
     *
     * <code>E_LOGOUT = 5002;</code>
     */
    public static final int E_LOGOUT_VALUE = 5002;
    /**
     * <pre>
     *创建账号
     * </pre>
     *
     * <code>E_CREATE_ACCOUNT = 5003;</code>
     */
    public static final int E_CREATE_ACCOUNT_VALUE = 5003;
    /**
     * <pre>
     *创建角色
     * </pre>
     *
     * <code>E_CREATE_PLAYER = 5004;</code>
     */
    public static final int E_CREATE_PLAYER_VALUE = 5004;
    /**
     * <code>E_LOGIN_END = 5999;</code>
     */
    public static final int E_LOGIN_END_VALUE = 5999;
    /**
     * <code>E_LOBBY_START = 6000;</code>
     */
    public static final int E_LOBBY_START_VALUE = 6000;
    /**
     * <code>E_ENTER_LOBBY = 6001;</code>
     */
    public static final int E_ENTER_LOBBY_VALUE = 6001;
    /**
     * <pre>
     *NOTIFY 25000~29999
     * </pre>
     *
     * <code>NOTIFY_COMMON_ERROR = 29999;</code>
     */
    public static final int NOTIFY_COMMON_ERROR_VALUE = 29999;
    /**
     * <code>E_LOBBY_END = 30000;</code>
     */
    public static final int E_LOBBY_END_VALUE = 30000;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EN_MessageId valueOf(int value) {
      return forNumber(value);
    }

    public static EN_MessageId forNumber(int value) {
      switch (value) {
        case 0: return E_ERROR_ID;
        case 1000: return E_ROOM_START;
        case 1001: return E_ROOM_CREATE;
        case 1002: return E_ROOM_HEART;
        case 1003: return E_ROOM_STATUS_CHANGE;
        case 1004: return E_ROOM_CLOSE;
        case 1005: return E_ROOM_ENTER_PLAYER;
        case 1006: return E_ROOM_QUIT_PLAYER;
        case 1007: return E_ROOM_BATTLE_REPORT;
        case 1500: return E_ROOM_END;
        case 5000: return E_LOGIN_START;
        case 5001: return E_LOGIN;
        case 5002: return E_LOGOUT;
        case 5003: return E_CREATE_ACCOUNT;
        case 5004: return E_CREATE_PLAYER;
        case 5999: return E_LOGIN_END;
        case 6000: return E_LOBBY_START;
        case 6001: return E_ENTER_LOBBY;
        case 29999: return NOTIFY_COMMON_ERROR;
        case 30000: return E_LOBBY_END;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EN_MessageId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EN_MessageId> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EN_MessageId>() {
            public EN_MessageId findValueByNumber(int number) {
              return EN_MessageId.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.rpc.message.st.MsgId.getDescriptor().getEnumTypes().get(0);
    }

    private static final EN_MessageId[] VALUES = values();

    public static EN_MessageId valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EN_MessageId(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.game.rpc.message.st.EN_MessageId)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013msgId.proto\022\027com.game.rpc.message.st*\253" +
      "\003\n\014EN_MessageId\022\016\n\nE_ERROR_ID\020\000\022\021\n\014E_ROO" +
      "M_START\020\350\007\022\022\n\rE_ROOM_CREATE\020\351\007\022\021\n\014E_ROOM" +
      "_HEART\020\352\007\022\031\n\024E_ROOM_STATUS_CHANGE\020\353\007\022\021\n\014" +
      "E_ROOM_CLOSE\020\354\007\022\030\n\023E_ROOM_ENTER_PLAYER\020\355" +
      "\007\022\027\n\022E_ROOM_QUIT_PLAYER\020\356\007\022\031\n\024E_ROOM_BAT" +
      "TLE_REPORT\020\357\007\022\017\n\nE_ROOM_END\020\334\013\022\022\n\rE_LOGI" +
      "N_START\020\210\'\022\014\n\007E_LOGIN\020\211\'\022\r\n\010E_LOGOUT\020\212\'\022" +
      "\025\n\020E_CREATE_ACCOUNT\020\213\'\022\024\n\017E_CREATE_PLAYE" +
      "R\020\214\'\022\020\n\013E_LOGIN_END\020\357.\022\022\n\rE_LOBBY_START\020" +
      "\360.\022\022\n\rE_ENTER_LOBBY\020\361.\022\031\n\023NOTIFY_COMMON_" +
      "ERROR\020\257\352\001\022\021\n\013E_LOBBY_END\020\260\352\001B \n\027com.game" +
      ".rpc.message.stB\005MsgIdb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
