// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.game.rpc.message.st.common;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.rpc.message.st.common.Player)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户标识ID
     * </pre>
     *
     * <code>string uqId = 1;</code>
     */
    java.lang.String getUqId();
    /**
     * <pre>
     *用户标识ID
     * </pre>
     *
     * <code>string uqId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUqIdBytes();

    /**
     * <pre>
     *用户昵称
     * </pre>
     *
     * <code>string nickname = 2;</code>
     */
    java.lang.String getNickname();
    /**
     * <pre>
     *用户昵称
     * </pre>
     *
     * <code>string nickname = 2;</code>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <pre>
     *等级
     * </pre>
     *
     * <code>int32 level = 3;</code>
     */
    int getLevel();

    /**
     * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
     */
    boolean hasSkillStore();
    /**
     * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
     */
    com.game.rpc.message.st.common.Common.SkillStore getSkillStore();
    /**
     * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
     */
    com.game.rpc.message.st.common.Common.SkillStoreOrBuilder getSkillStoreOrBuilder();

    /**
     * <pre>
     *卡牌列表
     * </pre>
     *
     * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
     */
    java.util.List<com.game.rpc.message.st.common.Common.Card> 
        getCardsList();
    /**
     * <pre>
     *卡牌列表
     * </pre>
     *
     * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
     */
    com.game.rpc.message.st.common.Common.Card getCards(int index);
    /**
     * <pre>
     *卡牌列表
     * </pre>
     *
     * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
     */
    int getCardsCount();
    /**
     * <pre>
     *卡牌列表
     * </pre>
     *
     * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
     */
    java.util.List<? extends com.game.rpc.message.st.common.Common.CardOrBuilder> 
        getCardsOrBuilderList();
    /**
     * <pre>
     *卡牌列表
     * </pre>
     *
     * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
     */
    com.game.rpc.message.st.common.Common.CardOrBuilder getCardsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.game.rpc.message.st.common.Player}
   */
  public  static final class Player extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.rpc.message.st.common.Player)
      PlayerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Player.newBuilder() to construct.
    private Player(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Player() {
      uqId_ = "";
      nickname_ = "";
      level_ = 0;
      cards_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Player(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uqId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nickname_ = s;
              break;
            }
            case 24: {

              level_ = input.readInt32();
              break;
            }
            case 34: {
              com.game.rpc.message.st.common.Common.SkillStore.Builder subBuilder = null;
              if (skillStore_ != null) {
                subBuilder = skillStore_.toBuilder();
              }
              skillStore_ = input.readMessage(com.game.rpc.message.st.common.Common.SkillStore.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(skillStore_);
                skillStore_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                cards_ = new java.util.ArrayList<com.game.rpc.message.st.common.Common.Card>();
                mutable_bitField0_ |= 0x00000010;
              }
              cards_.add(
                  input.readMessage(com.game.rpc.message.st.common.Common.Card.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          cards_ = java.util.Collections.unmodifiableList(cards_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_Player_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.rpc.message.st.common.Common.Player.class, com.game.rpc.message.st.common.Common.Player.Builder.class);
    }

    private int bitField0_;
    public static final int UQID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uqId_;
    /**
     * <pre>
     *用户标识ID
     * </pre>
     *
     * <code>string uqId = 1;</code>
     */
    public java.lang.String getUqId() {
      java.lang.Object ref = uqId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uqId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户标识ID
     * </pre>
     *
     * <code>string uqId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUqIdBytes() {
      java.lang.Object ref = uqId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nickname_;
    /**
     * <pre>
     *用户昵称
     * </pre>
     *
     * <code>string nickname = 2;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户昵称
     * </pre>
     *
     * <code>string nickname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <pre>
     *等级
     * </pre>
     *
     * <code>int32 level = 3;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int SKILL_STORE_FIELD_NUMBER = 4;
    private com.game.rpc.message.st.common.Common.SkillStore skillStore_;
    /**
     * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
     */
    public boolean hasSkillStore() {
      return skillStore_ != null;
    }
    /**
     * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
     */
    public com.game.rpc.message.st.common.Common.SkillStore getSkillStore() {
      return skillStore_ == null ? com.game.rpc.message.st.common.Common.SkillStore.getDefaultInstance() : skillStore_;
    }
    /**
     * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
     */
    public com.game.rpc.message.st.common.Common.SkillStoreOrBuilder getSkillStoreOrBuilder() {
      return getSkillStore();
    }

    public static final int CARDS_FIELD_NUMBER = 5;
    private java.util.List<com.game.rpc.message.st.common.Common.Card> cards_;
    /**
     * <pre>
     *卡牌列表
     * </pre>
     *
     * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
     */
    public java.util.List<com.game.rpc.message.st.common.Common.Card> getCardsList() {
      return cards_;
    }
    /**
     * <pre>
     *卡牌列表
     * </pre>
     *
     * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
     */
    public java.util.List<? extends com.game.rpc.message.st.common.Common.CardOrBuilder> 
        getCardsOrBuilderList() {
      return cards_;
    }
    /**
     * <pre>
     *卡牌列表
     * </pre>
     *
     * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
     */
    public int getCardsCount() {
      return cards_.size();
    }
    /**
     * <pre>
     *卡牌列表
     * </pre>
     *
     * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
     */
    public com.game.rpc.message.st.common.Common.Card getCards(int index) {
      return cards_.get(index);
    }
    /**
     * <pre>
     *卡牌列表
     * </pre>
     *
     * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
     */
    public com.game.rpc.message.st.common.Common.CardOrBuilder getCardsOrBuilder(
        int index) {
      return cards_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUqIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uqId_);
      }
      if (!getNicknameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nickname_);
      }
      if (level_ != 0) {
        output.writeInt32(3, level_);
      }
      if (skillStore_ != null) {
        output.writeMessage(4, getSkillStore());
      }
      for (int i = 0; i < cards_.size(); i++) {
        output.writeMessage(5, cards_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUqIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uqId_);
      }
      if (!getNicknameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nickname_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (skillStore_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSkillStore());
      }
      for (int i = 0; i < cards_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, cards_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.rpc.message.st.common.Common.Player)) {
        return super.equals(obj);
      }
      com.game.rpc.message.st.common.Common.Player other = (com.game.rpc.message.st.common.Common.Player) obj;

      boolean result = true;
      result = result && getUqId()
          .equals(other.getUqId());
      result = result && getNickname()
          .equals(other.getNickname());
      result = result && (getLevel()
          == other.getLevel());
      result = result && (hasSkillStore() == other.hasSkillStore());
      if (hasSkillStore()) {
        result = result && getSkillStore()
            .equals(other.getSkillStore());
      }
      result = result && getCardsList()
          .equals(other.getCardsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UQID_FIELD_NUMBER;
      hash = (53 * hash) + getUqId().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickname().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      if (hasSkillStore()) {
        hash = (37 * hash) + SKILL_STORE_FIELD_NUMBER;
        hash = (53 * hash) + getSkillStore().hashCode();
      }
      if (getCardsCount() > 0) {
        hash = (37 * hash) + CARDS_FIELD_NUMBER;
        hash = (53 * hash) + getCardsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.rpc.message.st.common.Common.Player parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.rpc.message.st.common.Common.Player parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.Player parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.rpc.message.st.common.Common.Player parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.Player parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.rpc.message.st.common.Common.Player parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.Player parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.rpc.message.st.common.Common.Player parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.Player parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.rpc.message.st.common.Common.Player parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.Player parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.rpc.message.st.common.Common.Player parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.rpc.message.st.common.Common.Player prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.rpc.message.st.common.Player}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.rpc.message.st.common.Player)
        com.game.rpc.message.st.common.Common.PlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_Player_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_Player_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.rpc.message.st.common.Common.Player.class, com.game.rpc.message.st.common.Common.Player.Builder.class);
      }

      // Construct using com.game.rpc.message.st.common.Common.Player.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCardsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        uqId_ = "";

        nickname_ = "";

        level_ = 0;

        if (skillStoreBuilder_ == null) {
          skillStore_ = null;
        } else {
          skillStore_ = null;
          skillStoreBuilder_ = null;
        }
        if (cardsBuilder_ == null) {
          cards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          cardsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_Player_descriptor;
      }

      public com.game.rpc.message.st.common.Common.Player getDefaultInstanceForType() {
        return com.game.rpc.message.st.common.Common.Player.getDefaultInstance();
      }

      public com.game.rpc.message.st.common.Common.Player build() {
        com.game.rpc.message.st.common.Common.Player result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.rpc.message.st.common.Common.Player buildPartial() {
        com.game.rpc.message.st.common.Common.Player result = new com.game.rpc.message.st.common.Common.Player(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.uqId_ = uqId_;
        result.nickname_ = nickname_;
        result.level_ = level_;
        if (skillStoreBuilder_ == null) {
          result.skillStore_ = skillStore_;
        } else {
          result.skillStore_ = skillStoreBuilder_.build();
        }
        if (cardsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            cards_ = java.util.Collections.unmodifiableList(cards_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.cards_ = cards_;
        } else {
          result.cards_ = cardsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.rpc.message.st.common.Common.Player) {
          return mergeFrom((com.game.rpc.message.st.common.Common.Player)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.rpc.message.st.common.Common.Player other) {
        if (other == com.game.rpc.message.st.common.Common.Player.getDefaultInstance()) return this;
        if (!other.getUqId().isEmpty()) {
          uqId_ = other.uqId_;
          onChanged();
        }
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          onChanged();
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.hasSkillStore()) {
          mergeSkillStore(other.getSkillStore());
        }
        if (cardsBuilder_ == null) {
          if (!other.cards_.isEmpty()) {
            if (cards_.isEmpty()) {
              cards_ = other.cards_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureCardsIsMutable();
              cards_.addAll(other.cards_);
            }
            onChanged();
          }
        } else {
          if (!other.cards_.isEmpty()) {
            if (cardsBuilder_.isEmpty()) {
              cardsBuilder_.dispose();
              cardsBuilder_ = null;
              cards_ = other.cards_;
              bitField0_ = (bitField0_ & ~0x00000010);
              cardsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCardsFieldBuilder() : null;
            } else {
              cardsBuilder_.addAllMessages(other.cards_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.rpc.message.st.common.Common.Player parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.rpc.message.st.common.Common.Player) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uqId_ = "";
      /**
       * <pre>
       *用户标识ID
       * </pre>
       *
       * <code>string uqId = 1;</code>
       */
      public java.lang.String getUqId() {
        java.lang.Object ref = uqId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uqId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户标识ID
       * </pre>
       *
       * <code>string uqId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUqIdBytes() {
        java.lang.Object ref = uqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户标识ID
       * </pre>
       *
       * <code>string uqId = 1;</code>
       */
      public Builder setUqId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户标识ID
       * </pre>
       *
       * <code>string uqId = 1;</code>
       */
      public Builder clearUqId() {
        
        uqId_ = getDefaultInstance().getUqId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户标识ID
       * </pre>
       *
       * <code>string uqId = 1;</code>
       */
      public Builder setUqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uqId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <pre>
       *用户昵称
       * </pre>
       *
       * <code>string nickname = 2;</code>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户昵称
       * </pre>
       *
       * <code>string nickname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户昵称
       * </pre>
       *
       * <code>string nickname = 2;</code>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户昵称
       * </pre>
       *
       * <code>string nickname = 2;</code>
       */
      public Builder clearNickname() {
        
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户昵称
       * </pre>
       *
       * <code>string nickname = 2;</code>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickname_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <pre>
       *等级
       * </pre>
       *
       * <code>int32 level = 3;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <pre>
       *等级
       * </pre>
       *
       * <code>int32 level = 3;</code>
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *等级
       * </pre>
       *
       * <code>int32 level = 3;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private com.game.rpc.message.st.common.Common.SkillStore skillStore_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.game.rpc.message.st.common.Common.SkillStore, com.game.rpc.message.st.common.Common.SkillStore.Builder, com.game.rpc.message.st.common.Common.SkillStoreOrBuilder> skillStoreBuilder_;
      /**
       * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
       */
      public boolean hasSkillStore() {
        return skillStoreBuilder_ != null || skillStore_ != null;
      }
      /**
       * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
       */
      public com.game.rpc.message.st.common.Common.SkillStore getSkillStore() {
        if (skillStoreBuilder_ == null) {
          return skillStore_ == null ? com.game.rpc.message.st.common.Common.SkillStore.getDefaultInstance() : skillStore_;
        } else {
          return skillStoreBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
       */
      public Builder setSkillStore(com.game.rpc.message.st.common.Common.SkillStore value) {
        if (skillStoreBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          skillStore_ = value;
          onChanged();
        } else {
          skillStoreBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
       */
      public Builder setSkillStore(
          com.game.rpc.message.st.common.Common.SkillStore.Builder builderForValue) {
        if (skillStoreBuilder_ == null) {
          skillStore_ = builderForValue.build();
          onChanged();
        } else {
          skillStoreBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
       */
      public Builder mergeSkillStore(com.game.rpc.message.st.common.Common.SkillStore value) {
        if (skillStoreBuilder_ == null) {
          if (skillStore_ != null) {
            skillStore_ =
              com.game.rpc.message.st.common.Common.SkillStore.newBuilder(skillStore_).mergeFrom(value).buildPartial();
          } else {
            skillStore_ = value;
          }
          onChanged();
        } else {
          skillStoreBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
       */
      public Builder clearSkillStore() {
        if (skillStoreBuilder_ == null) {
          skillStore_ = null;
          onChanged();
        } else {
          skillStore_ = null;
          skillStoreBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
       */
      public com.game.rpc.message.st.common.Common.SkillStore.Builder getSkillStoreBuilder() {
        
        onChanged();
        return getSkillStoreFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
       */
      public com.game.rpc.message.st.common.Common.SkillStoreOrBuilder getSkillStoreOrBuilder() {
        if (skillStoreBuilder_ != null) {
          return skillStoreBuilder_.getMessageOrBuilder();
        } else {
          return skillStore_ == null ?
              com.game.rpc.message.st.common.Common.SkillStore.getDefaultInstance() : skillStore_;
        }
      }
      /**
       * <code>.com.game.rpc.message.st.common.SkillStore skill_store = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.game.rpc.message.st.common.Common.SkillStore, com.game.rpc.message.st.common.Common.SkillStore.Builder, com.game.rpc.message.st.common.Common.SkillStoreOrBuilder> 
          getSkillStoreFieldBuilder() {
        if (skillStoreBuilder_ == null) {
          skillStoreBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.game.rpc.message.st.common.Common.SkillStore, com.game.rpc.message.st.common.Common.SkillStore.Builder, com.game.rpc.message.st.common.Common.SkillStoreOrBuilder>(
                  getSkillStore(),
                  getParentForChildren(),
                  isClean());
          skillStore_ = null;
        }
        return skillStoreBuilder_;
      }

      private java.util.List<com.game.rpc.message.st.common.Common.Card> cards_ =
        java.util.Collections.emptyList();
      private void ensureCardsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          cards_ = new java.util.ArrayList<com.game.rpc.message.st.common.Common.Card>(cards_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.game.rpc.message.st.common.Common.Card, com.game.rpc.message.st.common.Common.Card.Builder, com.game.rpc.message.st.common.Common.CardOrBuilder> cardsBuilder_;

      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public java.util.List<com.game.rpc.message.st.common.Common.Card> getCardsList() {
        if (cardsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cards_);
        } else {
          return cardsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public int getCardsCount() {
        if (cardsBuilder_ == null) {
          return cards_.size();
        } else {
          return cardsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public com.game.rpc.message.st.common.Common.Card getCards(int index) {
        if (cardsBuilder_ == null) {
          return cards_.get(index);
        } else {
          return cardsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public Builder setCards(
          int index, com.game.rpc.message.st.common.Common.Card value) {
        if (cardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardsIsMutable();
          cards_.set(index, value);
          onChanged();
        } else {
          cardsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public Builder setCards(
          int index, com.game.rpc.message.st.common.Common.Card.Builder builderForValue) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.set(index, builderForValue.build());
          onChanged();
        } else {
          cardsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public Builder addCards(com.game.rpc.message.st.common.Common.Card value) {
        if (cardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardsIsMutable();
          cards_.add(value);
          onChanged();
        } else {
          cardsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public Builder addCards(
          int index, com.game.rpc.message.st.common.Common.Card value) {
        if (cardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardsIsMutable();
          cards_.add(index, value);
          onChanged();
        } else {
          cardsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public Builder addCards(
          com.game.rpc.message.st.common.Common.Card.Builder builderForValue) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.add(builderForValue.build());
          onChanged();
        } else {
          cardsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public Builder addCards(
          int index, com.game.rpc.message.st.common.Common.Card.Builder builderForValue) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.add(index, builderForValue.build());
          onChanged();
        } else {
          cardsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public Builder addAllCards(
          java.lang.Iterable<? extends com.game.rpc.message.st.common.Common.Card> values) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cards_);
          onChanged();
        } else {
          cardsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public Builder clearCards() {
        if (cardsBuilder_ == null) {
          cards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          cardsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public Builder removeCards(int index) {
        if (cardsBuilder_ == null) {
          ensureCardsIsMutable();
          cards_.remove(index);
          onChanged();
        } else {
          cardsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public com.game.rpc.message.st.common.Common.Card.Builder getCardsBuilder(
          int index) {
        return getCardsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public com.game.rpc.message.st.common.Common.CardOrBuilder getCardsOrBuilder(
          int index) {
        if (cardsBuilder_ == null) {
          return cards_.get(index);  } else {
          return cardsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public java.util.List<? extends com.game.rpc.message.st.common.Common.CardOrBuilder> 
           getCardsOrBuilderList() {
        if (cardsBuilder_ != null) {
          return cardsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cards_);
        }
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public com.game.rpc.message.st.common.Common.Card.Builder addCardsBuilder() {
        return getCardsFieldBuilder().addBuilder(
            com.game.rpc.message.st.common.Common.Card.getDefaultInstance());
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public com.game.rpc.message.st.common.Common.Card.Builder addCardsBuilder(
          int index) {
        return getCardsFieldBuilder().addBuilder(
            index, com.game.rpc.message.st.common.Common.Card.getDefaultInstance());
      }
      /**
       * <pre>
       *卡牌列表
       * </pre>
       *
       * <code>repeated .com.game.rpc.message.st.common.Card cards = 5;</code>
       */
      public java.util.List<com.game.rpc.message.st.common.Common.Card.Builder> 
           getCardsBuilderList() {
        return getCardsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.game.rpc.message.st.common.Common.Card, com.game.rpc.message.st.common.Common.Card.Builder, com.game.rpc.message.st.common.Common.CardOrBuilder> 
          getCardsFieldBuilder() {
        if (cardsBuilder_ == null) {
          cardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.game.rpc.message.st.common.Common.Card, com.game.rpc.message.st.common.Common.Card.Builder, com.game.rpc.message.st.common.Common.CardOrBuilder>(
                  cards_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          cards_ = null;
        }
        return cardsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.game.rpc.message.st.common.Player)
    }

    // @@protoc_insertion_point(class_scope:com.game.rpc.message.st.common.Player)
    private static final com.game.rpc.message.st.common.Common.Player DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.rpc.message.st.common.Common.Player();
    }

    public static com.game.rpc.message.st.common.Common.Player getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Player>
        PARSER = new com.google.protobuf.AbstractParser<Player>() {
      public Player parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Player(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Player> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Player> getParserForType() {
      return PARSER;
    }

    public com.game.rpc.message.st.common.Common.Player getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SkillStoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.rpc.message.st.common.SkillStore)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *技能ID
     * </pre>
     *
     * <code>int32 skillId = 1;</code>
     */
    int getSkillId();

    /**
     * <pre>
     *技能是否设置为使用
     * </pre>
     *
     * <code>bool use = 2;</code>
     */
    boolean getUse();
  }
  /**
   * Protobuf type {@code com.game.rpc.message.st.common.SkillStore}
   */
  public  static final class SkillStore extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.rpc.message.st.common.SkillStore)
      SkillStoreOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SkillStore.newBuilder() to construct.
    private SkillStore(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SkillStore() {
      skillId_ = 0;
      use_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SkillStore(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              skillId_ = input.readInt32();
              break;
            }
            case 16: {

              use_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_SkillStore_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_SkillStore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.rpc.message.st.common.Common.SkillStore.class, com.game.rpc.message.st.common.Common.SkillStore.Builder.class);
    }

    public static final int SKILLID_FIELD_NUMBER = 1;
    private int skillId_;
    /**
     * <pre>
     *技能ID
     * </pre>
     *
     * <code>int32 skillId = 1;</code>
     */
    public int getSkillId() {
      return skillId_;
    }

    public static final int USE_FIELD_NUMBER = 2;
    private boolean use_;
    /**
     * <pre>
     *技能是否设置为使用
     * </pre>
     *
     * <code>bool use = 2;</code>
     */
    public boolean getUse() {
      return use_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (skillId_ != 0) {
        output.writeInt32(1, skillId_);
      }
      if (use_ != false) {
        output.writeBool(2, use_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (skillId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, skillId_);
      }
      if (use_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, use_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.rpc.message.st.common.Common.SkillStore)) {
        return super.equals(obj);
      }
      com.game.rpc.message.st.common.Common.SkillStore other = (com.game.rpc.message.st.common.Common.SkillStore) obj;

      boolean result = true;
      result = result && (getSkillId()
          == other.getSkillId());
      result = result && (getUse()
          == other.getUse());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SKILLID_FIELD_NUMBER;
      hash = (53 * hash) + getSkillId();
      hash = (37 * hash) + USE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUse());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.rpc.message.st.common.Common.SkillStore parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.rpc.message.st.common.Common.SkillStore parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.SkillStore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.rpc.message.st.common.Common.SkillStore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.SkillStore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.rpc.message.st.common.Common.SkillStore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.SkillStore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.rpc.message.st.common.Common.SkillStore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.SkillStore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.rpc.message.st.common.Common.SkillStore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.SkillStore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.rpc.message.st.common.Common.SkillStore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.rpc.message.st.common.Common.SkillStore prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.rpc.message.st.common.SkillStore}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.rpc.message.st.common.SkillStore)
        com.game.rpc.message.st.common.Common.SkillStoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_SkillStore_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_SkillStore_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.rpc.message.st.common.Common.SkillStore.class, com.game.rpc.message.st.common.Common.SkillStore.Builder.class);
      }

      // Construct using com.game.rpc.message.st.common.Common.SkillStore.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        skillId_ = 0;

        use_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_SkillStore_descriptor;
      }

      public com.game.rpc.message.st.common.Common.SkillStore getDefaultInstanceForType() {
        return com.game.rpc.message.st.common.Common.SkillStore.getDefaultInstance();
      }

      public com.game.rpc.message.st.common.Common.SkillStore build() {
        com.game.rpc.message.st.common.Common.SkillStore result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.rpc.message.st.common.Common.SkillStore buildPartial() {
        com.game.rpc.message.st.common.Common.SkillStore result = new com.game.rpc.message.st.common.Common.SkillStore(this);
        result.skillId_ = skillId_;
        result.use_ = use_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.rpc.message.st.common.Common.SkillStore) {
          return mergeFrom((com.game.rpc.message.st.common.Common.SkillStore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.rpc.message.st.common.Common.SkillStore other) {
        if (other == com.game.rpc.message.st.common.Common.SkillStore.getDefaultInstance()) return this;
        if (other.getSkillId() != 0) {
          setSkillId(other.getSkillId());
        }
        if (other.getUse() != false) {
          setUse(other.getUse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.rpc.message.st.common.Common.SkillStore parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.rpc.message.st.common.Common.SkillStore) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int skillId_ ;
      /**
       * <pre>
       *技能ID
       * </pre>
       *
       * <code>int32 skillId = 1;</code>
       */
      public int getSkillId() {
        return skillId_;
      }
      /**
       * <pre>
       *技能ID
       * </pre>
       *
       * <code>int32 skillId = 1;</code>
       */
      public Builder setSkillId(int value) {
        
        skillId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *技能ID
       * </pre>
       *
       * <code>int32 skillId = 1;</code>
       */
      public Builder clearSkillId() {
        
        skillId_ = 0;
        onChanged();
        return this;
      }

      private boolean use_ ;
      /**
       * <pre>
       *技能是否设置为使用
       * </pre>
       *
       * <code>bool use = 2;</code>
       */
      public boolean getUse() {
        return use_;
      }
      /**
       * <pre>
       *技能是否设置为使用
       * </pre>
       *
       * <code>bool use = 2;</code>
       */
      public Builder setUse(boolean value) {
        
        use_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *技能是否设置为使用
       * </pre>
       *
       * <code>bool use = 2;</code>
       */
      public Builder clearUse() {
        
        use_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.game.rpc.message.st.common.SkillStore)
    }

    // @@protoc_insertion_point(class_scope:com.game.rpc.message.st.common.SkillStore)
    private static final com.game.rpc.message.st.common.Common.SkillStore DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.rpc.message.st.common.Common.SkillStore();
    }

    public static com.game.rpc.message.st.common.Common.SkillStore getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SkillStore>
        PARSER = new com.google.protobuf.AbstractParser<SkillStore>() {
      public SkillStore parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SkillStore(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SkillStore> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SkillStore> getParserForType() {
      return PARSER;
    }

    public com.game.rpc.message.st.common.Common.SkillStore getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.game.rpc.message.st.common.Card)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 card_id = 1;</code>
     */
    int getCardId();

    /**
     * <code>int32 card_level = 2;</code>
     */
    int getCardLevel();
  }
  /**
   * Protobuf type {@code com.game.rpc.message.st.common.Card}
   */
  public  static final class Card extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.game.rpc.message.st.common.Card)
      CardOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Card.newBuilder() to construct.
    private Card(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Card() {
      cardId_ = 0;
      cardLevel_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Card(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cardId_ = input.readInt32();
              break;
            }
            case 16: {

              cardLevel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_Card_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_Card_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.rpc.message.st.common.Common.Card.class, com.game.rpc.message.st.common.Common.Card.Builder.class);
    }

    public static final int CARD_ID_FIELD_NUMBER = 1;
    private int cardId_;
    /**
     * <code>int32 card_id = 1;</code>
     */
    public int getCardId() {
      return cardId_;
    }

    public static final int CARD_LEVEL_FIELD_NUMBER = 2;
    private int cardLevel_;
    /**
     * <code>int32 card_level = 2;</code>
     */
    public int getCardLevel() {
      return cardLevel_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cardId_ != 0) {
        output.writeInt32(1, cardId_);
      }
      if (cardLevel_ != 0) {
        output.writeInt32(2, cardLevel_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cardId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cardId_);
      }
      if (cardLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cardLevel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.rpc.message.st.common.Common.Card)) {
        return super.equals(obj);
      }
      com.game.rpc.message.st.common.Common.Card other = (com.game.rpc.message.st.common.Common.Card) obj;

      boolean result = true;
      result = result && (getCardId()
          == other.getCardId());
      result = result && (getCardLevel()
          == other.getCardLevel());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CARD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCardId();
      hash = (37 * hash) + CARD_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getCardLevel();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.rpc.message.st.common.Common.Card parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.rpc.message.st.common.Common.Card parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.Card parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.rpc.message.st.common.Common.Card parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.Card parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.rpc.message.st.common.Common.Card parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.Card parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.rpc.message.st.common.Common.Card parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.Card parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.rpc.message.st.common.Common.Card parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.rpc.message.st.common.Common.Card parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.rpc.message.st.common.Common.Card parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.rpc.message.st.common.Common.Card prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.game.rpc.message.st.common.Card}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.game.rpc.message.st.common.Card)
        com.game.rpc.message.st.common.Common.CardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_Card_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_Card_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.rpc.message.st.common.Common.Card.class, com.game.rpc.message.st.common.Common.Card.Builder.class);
      }

      // Construct using com.game.rpc.message.st.common.Common.Card.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cardId_ = 0;

        cardLevel_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.rpc.message.st.common.Common.internal_static_com_game_rpc_message_st_common_Card_descriptor;
      }

      public com.game.rpc.message.st.common.Common.Card getDefaultInstanceForType() {
        return com.game.rpc.message.st.common.Common.Card.getDefaultInstance();
      }

      public com.game.rpc.message.st.common.Common.Card build() {
        com.game.rpc.message.st.common.Common.Card result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.game.rpc.message.st.common.Common.Card buildPartial() {
        com.game.rpc.message.st.common.Common.Card result = new com.game.rpc.message.st.common.Common.Card(this);
        result.cardId_ = cardId_;
        result.cardLevel_ = cardLevel_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.rpc.message.st.common.Common.Card) {
          return mergeFrom((com.game.rpc.message.st.common.Common.Card)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.rpc.message.st.common.Common.Card other) {
        if (other == com.game.rpc.message.st.common.Common.Card.getDefaultInstance()) return this;
        if (other.getCardId() != 0) {
          setCardId(other.getCardId());
        }
        if (other.getCardLevel() != 0) {
          setCardLevel(other.getCardLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.rpc.message.st.common.Common.Card parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.rpc.message.st.common.Common.Card) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cardId_ ;
      /**
       * <code>int32 card_id = 1;</code>
       */
      public int getCardId() {
        return cardId_;
      }
      /**
       * <code>int32 card_id = 1;</code>
       */
      public Builder setCardId(int value) {
        
        cardId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 card_id = 1;</code>
       */
      public Builder clearCardId() {
        
        cardId_ = 0;
        onChanged();
        return this;
      }

      private int cardLevel_ ;
      /**
       * <code>int32 card_level = 2;</code>
       */
      public int getCardLevel() {
        return cardLevel_;
      }
      /**
       * <code>int32 card_level = 2;</code>
       */
      public Builder setCardLevel(int value) {
        
        cardLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 card_level = 2;</code>
       */
      public Builder clearCardLevel() {
        
        cardLevel_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.game.rpc.message.st.common.Card)
    }

    // @@protoc_insertion_point(class_scope:com.game.rpc.message.st.common.Card)
    private static final com.game.rpc.message.st.common.Common.Card DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.rpc.message.st.common.Common.Card();
    }

    public static com.game.rpc.message.st.common.Common.Card getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Card>
        PARSER = new com.google.protobuf.AbstractParser<Card>() {
      public Card parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Card(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Card> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Card> getParserForType() {
      return PARSER;
    }

    public com.game.rpc.message.st.common.Common.Card getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_rpc_message_st_common_Player_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_rpc_message_st_common_Player_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_rpc_message_st_common_SkillStore_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_rpc_message_st_common_SkillStore_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_game_rpc_message_st_common_Card_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_game_rpc_message_st_common_Card_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\036com.game.rpc.message.st." +
      "common\"\255\001\n\006Player\022\014\n\004uqId\030\001 \001(\t\022\020\n\010nickn" +
      "ame\030\002 \001(\t\022\r\n\005level\030\003 \001(\005\022?\n\013skill_store\030" +
      "\004 \001(\0132*.com.game.rpc.message.st.common.S" +
      "killStore\0223\n\005cards\030\005 \003(\0132$.com.game.rpc." +
      "message.st.common.Card\"*\n\nSkillStore\022\017\n\007" +
      "skillId\030\001 \001(\005\022\013\n\003use\030\002 \001(\010\"+\n\004Card\022\017\n\007ca" +
      "rd_id\030\001 \001(\005\022\022\n\ncard_level\030\002 \001(\005B(\n\036com.g" +
      "ame.rpc.message.st.commonB\006Commonb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_game_rpc_message_st_common_Player_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_game_rpc_message_st_common_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_rpc_message_st_common_Player_descriptor,
        new java.lang.String[] { "UqId", "Nickname", "Level", "SkillStore", "Cards", });
    internal_static_com_game_rpc_message_st_common_SkillStore_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_game_rpc_message_st_common_SkillStore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_rpc_message_st_common_SkillStore_descriptor,
        new java.lang.String[] { "SkillId", "Use", });
    internal_static_com_game_rpc_message_st_common_Card_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_game_rpc_message_st_common_Card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_game_rpc_message_st_common_Card_descriptor,
        new java.lang.String[] { "CardId", "CardLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
